### PR TITLE
Add rustfmt.toml to configure formatter

### PR DESCRIPTION
**Pull request by sbernauer**
Merge this after https://github.com/stackabletech/secret-operator/pull/125 get's merged and didn't case any problems
I had a quick chat with @soenkeliebau and we agreed to give it a try

### CODE REVIEW

**Comment by soenkeliebau** [comment]
The "issue" with this is, that it requires the unstable toolchain to work, so we won't introduce any checks around this, the file is purely there as an offer, if you want to use it in your operator then that is fine and this way we ensure that is is configured the same everywhere, but if you don't feel like switching to the nightly chain to run this then that is fine too.

**Review by soenkeliebau — APPROVED** [review]

**Comment by teozkr** [comment]
For what it's worth, you can run a single cargo command using the nightly toolchain by using `cargo +nightly fmt`.

Rust-Analyzer should also allow you to set rustfmt-specific flags (for Emacs, put `(setq rust-rustfmt-switches '("+nightly" "--edition" "2018"))` into your `.emacs`), and I assume Rust-IntelliJ has something similar.

**Comment by sbernauer** [comment]
Let's try that out

**Pull request merged**
