### PR TITLE
chore: Allow OpenSSL license (needed for ring and aws-lc-sys crates)

### PR DESCRIPTION
**Pull request by sbernauer**
Came up in https://github.com/stackabletech/operator-rs/pull/907#discussion_r1848217771

```
error[rejected]: failed to satisfy license requirements
  ┌─ registry+https://github.com/rust-lang/crates.io-index#aws-lc-sys@0.22.0:4:44
  │
4 │ license = "ISC AND (Apache-2.0 OR ISC) AND OpenSSL"
  │            ────────────────────────────────━━━━━━━
  │            │                               │
  │            │                               rejected: license is not explicitly allowed
  │            license expression retrieved via Cargo.toml `license`
  │
  ├ OpenSSL - OpenSSL License:
  ├   - FSF Free/Libre
  ├ aws-lc-sys v0.22.0
    └── aws-lc-rs v1.10.0
        ├── rustls v0.23.15
        │   ├── hyper-rustls v0.27.3
        │   │   └── kube-client v0.96.0
        │   │       ├── kube v0.96.0
        │   │       │   ├── stackable-certs v0.3.1
        │   │       │   │   └── stackable-webhook v0.3.1
        │   │       │   │       └── (dev) stackable-telemetry v0.2.0
        │   │       │   │           └── stackable-webhook v0.3.1 (*)
        │   │       │   ├── stackable-operator v0.81.0
        │   │       │   │   ├── stackable-certs v0.3.1 (*)
        │   │       │   │   ├── (dev) stackable-operator-derive v0.3.1
        │   │       │   │   │   └── stackable-operator v0.81.0 (*)
        │   │       │   │   └── stackable-webhook v0.3.1 (*)
        │   │       │   ├── stackable-shared v0.0.1
        │   │       │   │   ├── stackable-operator v0.81.0 (*)
        │   │       │   │   ├── stackable-versioned v0.4.1
        │   │       │   │   │   └── (dev) stackable-versioned-macros v0.4.1
        │   │       │   │   │       └── stackable-versioned v0.4.1 (*)
        │   │       │   │   └── stackable-versioned-macros v0.4.1 (*)
        │   │       │   ├── stackable-versioned v0.4.1 (*)
        │   │       │   ├── stackable-versioned-macros v0.4.1 (*)
        │   │       │   └── stackable-webhook v0.3.1 (*)
        │   │       └── kube-runtime v0.96.0
        │   │           └── kube v0.96.0 (*)
        │   ├── kube-client v0.96.0 (*)
        │   └── tokio-rustls v0.26.0
        │       ├── hyper-rustls v0.27.3 (*)
        │       ├── stackable-certs v0.3.1 (*)
        │       └── stackable-webhook v0.3.1 (*)
        └── rustls-webpki v0.102.8
            └── rustls v0.23.15 (*)
```

### CODE REVIEW

**Comment by soenkeliebau** [comment]
https://github.com/stackabletech/operator-rs/pull/907#discussion_r1848442493

**Comment by soenkeliebau** [comment]
ping @lfrancke  for potential veto, I'd be happy merging this

**Comment by lfrancke** [comment]
I did not read this but I trust you. So go ahead.

**Comment by sbernauer** [comment]
So, it turns out both the aws-lc-sys and ring crates need the OpenSSL license. So I'd say we need to allow it in any case...

https://github.com/aws/aws-lc-rs/blob/cdb1651d7398148688fa4c0106135b4a82ec1e49/aws-lc-sys/Cargo.toml#L9
and
https://github.com/briansmith/ring/blob/main/LICENSE

@soenkeliebau can we merge this?

**Review by adwk67 — DISMISSED** [review]

**Review by NickLarsenNZ — APPROVED** [review]
LGTM.

Both @soenkeliebau and @lfrancke have said they're fine with it.

**Pull request merged**
