### PR TITLE
Add operator version to Antora manifest

### PR DESCRIPTION
**Pull request by teozkr**
Doing this manually got old quickly... :P

### CODE REVIEW

**Comment by fhennig** [comment]
Hey, thanks for picking this up! We actually came up with a ticket for it yesterday as well :D 

https://github.com/stackabletech/operator-templating/issues/140

Can you get these formatting changes in? (just 'nighly' for nightly versions and just `major.minor` for stable versions)

**Comment by teozkr** [comment]
I can change it to go back to nightly for the nightlies if required, but I think for releases that seems more like a presentation problem?

**Comment by fhennig** [comment]
I don' think this is just a representation issue. We talked about this yesterday, and using semantic versioning, a patch release should not contain new features or the like, so the documented featureset is identical across all patch versions. That is why we only distinguish `major.minor`. and not at the patch level.

Antora also supports a `display_version` field but that doesn't affect page IDs. if we were to just change the docs version tag to a new patch level if we release a new patch version, old links would break. This would not happen if we didn't include the patch level in the antora version.

**Comment by teozkr** [comment]
Ok, done.

**Comment by fhennig** [comment]
Thank you.

I ran it locally and got an error:
    
    yq eval -i '.version = nightly' /dev/stdin < docs/antora.yml
    Error: parsing expression: Lexer error: could not match text starting at 1:12 failing at 1:14.
	    unmatched text: "ni"
    make: *** [Makefile:45: version] Error 1

I ran the `test.sh` script.

This is the yq version I use: `yq (https://github.com/mikefarah/yq/) version 4.24.2`

**Comment by fhennig** [comment]
While we're at it, can we set the `prerelease` key to true for the nightly version?

https://docs.antora.org/antora/latest/component-prerelease/#true

This will allow us to properly mark the latest stable version as latest in the antora playbook

**Review by fhennig — APPROVED** [review]
Tested, very nice, thank you very much!

**Pull request merged**
